/* soapH.h
   Generated by gSOAP 2.8.15 from soapmsg.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_serialize_byte(soap, data), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_serialize_int(soap, data), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_long
#define SOAP_TYPE_long (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_long(struct soap*, long *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_long(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_long(struct soap*, const char*, long *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_long(struct soap*, const long *, const char*, const char*);

#ifndef soap_write_long
#define soap_write_long(soap, data) ( soap_serialize_long(soap, data), soap_begin_send(soap) || soap_put_long(soap, data, "long", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 long * SOAP_FMAC4 soap_get_long(struct soap*, long *, const char*, const char*);

#ifndef soap_read_long
#define soap_read_long(soap, data) ( soap_begin_recv(soap) || !soap_get_long(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);

#ifndef soap_write_unsignedByte
#define soap_write_unsignedByte(soap, data) ( soap_serialize_unsignedByte(soap, data), soap_begin_send(soap) || soap_put_unsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);

#ifndef soap_read_unsignedByte
#define soap_read_unsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);

#ifndef soap_write_unsignedInt
#define soap_write_unsignedInt(soap, data) ( soap_serialize_unsignedInt(soap, data), soap_begin_send(soap) || soap_put_unsignedInt(soap, data, "unsignedInt", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);

#ifndef soap_read_unsignedInt
#define soap_read_unsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_unsignedLong
#define SOAP_TYPE_unsignedLong (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedLong(struct soap*, unsigned long *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedLong(struct soap*, const char*, int, const unsigned long *, const char*);
SOAP_FMAC3 unsigned long * SOAP_FMAC4 soap_in_unsignedLong(struct soap*, const char*, unsigned long *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedLong(struct soap*, const unsigned long *, const char*, const char*);

#ifndef soap_write_unsignedLong
#define soap_write_unsignedLong(soap, data) ( soap_serialize_unsignedLong(soap, data), soap_begin_send(soap) || soap_put_unsignedLong(soap, data, "unsignedLong", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 unsigned long * SOAP_FMAC4 soap_get_unsignedLong(struct soap*, unsigned long *, const char*, const char*);

#ifndef soap_read_unsignedLong
#define soap_read_unsignedLong(soap, data) ( soap_begin_recv(soap) || !soap_get_unsignedLong(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_serialize_SOAP_ENV__Fault(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_serialize_SOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_serialize_SOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_serialize_SOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_serialize_SOAP_ENV__Header(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_ns__ATTGetAnalyse
#define SOAP_TYPE_ns__ATTGetAnalyse (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__ATTGetAnalyse(struct soap*, struct ns__ATTGetAnalyse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__ATTGetAnalyse(struct soap*, const struct ns__ATTGetAnalyse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ATTGetAnalyse(struct soap*, const char*, int, const struct ns__ATTGetAnalyse *, const char*);
SOAP_FMAC3 struct ns__ATTGetAnalyse * SOAP_FMAC4 soap_in_ns__ATTGetAnalyse(struct soap*, const char*, struct ns__ATTGetAnalyse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__ATTGetAnalyse(struct soap*, const struct ns__ATTGetAnalyse *, const char*, const char*);

#ifndef soap_write_ns__ATTGetAnalyse
#define soap_write_ns__ATTGetAnalyse(soap, data) ( soap_serialize_ns__ATTGetAnalyse(soap, data), soap_begin_send(soap) || soap_put_ns__ATTGetAnalyse(soap, data, "ns:ATTGetAnalyse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__ATTGetAnalyse * SOAP_FMAC4 soap_get_ns__ATTGetAnalyse(struct soap*, struct ns__ATTGetAnalyse *, const char*, const char*);

#ifndef soap_read_ns__ATTGetAnalyse
#define soap_read_ns__ATTGetAnalyse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ATTGetAnalyse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__ATTGetAnalyseResponse
#define SOAP_TYPE_ns__ATTGetAnalyseResponse (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__ATTGetAnalyseResponse(struct soap*, struct ns__ATTGetAnalyseResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__ATTGetAnalyseResponse(struct soap*, const struct ns__ATTGetAnalyseResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ATTGetAnalyseResponse(struct soap*, const char*, int, const struct ns__ATTGetAnalyseResponse *, const char*);
SOAP_FMAC3 struct ns__ATTGetAnalyseResponse * SOAP_FMAC4 soap_in_ns__ATTGetAnalyseResponse(struct soap*, const char*, struct ns__ATTGetAnalyseResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__ATTGetAnalyseResponse(struct soap*, const struct ns__ATTGetAnalyseResponse *, const char*, const char*);

#ifndef soap_write_ns__ATTGetAnalyseResponse
#define soap_write_ns__ATTGetAnalyseResponse(soap, data) ( soap_serialize_ns__ATTGetAnalyseResponse(soap, data), soap_begin_send(soap) || soap_put_ns__ATTGetAnalyseResponse(soap, data, "ns:ATTGetAnalyseResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__ATTGetAnalyseResponse * SOAP_FMAC4 soap_get_ns__ATTGetAnalyseResponse(struct soap*, struct ns__ATTGetAnalyseResponse *, const char*, const char*);

#ifndef soap_read_ns__ATTGetAnalyseResponse
#define soap_read_ns__ATTGetAnalyseResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ATTGetAnalyseResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__ATTGetAnalyseName
#define SOAP_TYPE_ns__ATTGetAnalyseName (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__ATTGetAnalyseName(struct soap*, struct ns__ATTGetAnalyseName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__ATTGetAnalyseName(struct soap*, const struct ns__ATTGetAnalyseName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ATTGetAnalyseName(struct soap*, const char*, int, const struct ns__ATTGetAnalyseName *, const char*);
SOAP_FMAC3 struct ns__ATTGetAnalyseName * SOAP_FMAC4 soap_in_ns__ATTGetAnalyseName(struct soap*, const char*, struct ns__ATTGetAnalyseName *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__ATTGetAnalyseName(struct soap*, const struct ns__ATTGetAnalyseName *, const char*, const char*);

#ifndef soap_write_ns__ATTGetAnalyseName
#define soap_write_ns__ATTGetAnalyseName(soap, data) ( soap_serialize_ns__ATTGetAnalyseName(soap, data), soap_begin_send(soap) || soap_put_ns__ATTGetAnalyseName(soap, data, "ns:ATTGetAnalyseName", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__ATTGetAnalyseName * SOAP_FMAC4 soap_get_ns__ATTGetAnalyseName(struct soap*, struct ns__ATTGetAnalyseName *, const char*, const char*);

#ifndef soap_read_ns__ATTGetAnalyseName
#define soap_read_ns__ATTGetAnalyseName(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ATTGetAnalyseName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__ATTGetAnalyseNameResponse
#define SOAP_TYPE_ns__ATTGetAnalyseNameResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__ATTGetAnalyseNameResponse(struct soap*, struct ns__ATTGetAnalyseNameResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__ATTGetAnalyseNameResponse(struct soap*, const struct ns__ATTGetAnalyseNameResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ATTGetAnalyseNameResponse(struct soap*, const char*, int, const struct ns__ATTGetAnalyseNameResponse *, const char*);
SOAP_FMAC3 struct ns__ATTGetAnalyseNameResponse * SOAP_FMAC4 soap_in_ns__ATTGetAnalyseNameResponse(struct soap*, const char*, struct ns__ATTGetAnalyseNameResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__ATTGetAnalyseNameResponse(struct soap*, const struct ns__ATTGetAnalyseNameResponse *, const char*, const char*);

#ifndef soap_write_ns__ATTGetAnalyseNameResponse
#define soap_write_ns__ATTGetAnalyseNameResponse(soap, data) ( soap_serialize_ns__ATTGetAnalyseNameResponse(soap, data), soap_begin_send(soap) || soap_put_ns__ATTGetAnalyseNameResponse(soap, data, "ns:ATTGetAnalyseNameResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__ATTGetAnalyseNameResponse * SOAP_FMAC4 soap_get_ns__ATTGetAnalyseNameResponse(struct soap*, struct ns__ATTGetAnalyseNameResponse *, const char*, const char*);

#ifndef soap_read_ns__ATTGetAnalyseNameResponse
#define soap_read_ns__ATTGetAnalyseNameResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ATTGetAnalyseNameResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__ATTGetTraceName
#define SOAP_TYPE_ns__ATTGetTraceName (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__ATTGetTraceName(struct soap*, struct ns__ATTGetTraceName *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__ATTGetTraceName(struct soap*, const struct ns__ATTGetTraceName *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ATTGetTraceName(struct soap*, const char*, int, const struct ns__ATTGetTraceName *, const char*);
SOAP_FMAC3 struct ns__ATTGetTraceName * SOAP_FMAC4 soap_in_ns__ATTGetTraceName(struct soap*, const char*, struct ns__ATTGetTraceName *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__ATTGetTraceName(struct soap*, const struct ns__ATTGetTraceName *, const char*, const char*);

#ifndef soap_write_ns__ATTGetTraceName
#define soap_write_ns__ATTGetTraceName(soap, data) ( soap_serialize_ns__ATTGetTraceName(soap, data), soap_begin_send(soap) || soap_put_ns__ATTGetTraceName(soap, data, "ns:ATTGetTraceName", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__ATTGetTraceName * SOAP_FMAC4 soap_get_ns__ATTGetTraceName(struct soap*, struct ns__ATTGetTraceName *, const char*, const char*);

#ifndef soap_read_ns__ATTGetTraceName
#define soap_read_ns__ATTGetTraceName(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ATTGetTraceName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__ATTGetTraceNameResponse
#define SOAP_TYPE_ns__ATTGetTraceNameResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__ATTGetTraceNameResponse(struct soap*, struct ns__ATTGetTraceNameResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__ATTGetTraceNameResponse(struct soap*, const struct ns__ATTGetTraceNameResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ATTGetTraceNameResponse(struct soap*, const char*, int, const struct ns__ATTGetTraceNameResponse *, const char*);
SOAP_FMAC3 struct ns__ATTGetTraceNameResponse * SOAP_FMAC4 soap_in_ns__ATTGetTraceNameResponse(struct soap*, const char*, struct ns__ATTGetTraceNameResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__ATTGetTraceNameResponse(struct soap*, const struct ns__ATTGetTraceNameResponse *, const char*, const char*);

#ifndef soap_write_ns__ATTGetTraceNameResponse
#define soap_write_ns__ATTGetTraceNameResponse(soap, data) ( soap_serialize_ns__ATTGetTraceNameResponse(soap, data), soap_begin_send(soap) || soap_put_ns__ATTGetTraceNameResponse(soap, data, "ns:ATTGetTraceNameResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__ATTGetTraceNameResponse * SOAP_FMAC4 soap_get_ns__ATTGetTraceNameResponse(struct soap*, struct ns__ATTGetTraceNameResponse *, const char*, const char*);

#ifndef soap_read_ns__ATTGetTraceNameResponse
#define soap_read_ns__ATTGetTraceNameResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ATTGetTraceNameResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__ATTGetSessionID
#define SOAP_TYPE_ns__ATTGetSessionID (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__ATTGetSessionID(struct soap*, struct ns__ATTGetSessionID *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__ATTGetSessionID(struct soap*, const struct ns__ATTGetSessionID *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ATTGetSessionID(struct soap*, const char*, int, const struct ns__ATTGetSessionID *, const char*);
SOAP_FMAC3 struct ns__ATTGetSessionID * SOAP_FMAC4 soap_in_ns__ATTGetSessionID(struct soap*, const char*, struct ns__ATTGetSessionID *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__ATTGetSessionID(struct soap*, const struct ns__ATTGetSessionID *, const char*, const char*);

#ifndef soap_write_ns__ATTGetSessionID
#define soap_write_ns__ATTGetSessionID(soap, data) ( soap_serialize_ns__ATTGetSessionID(soap, data), soap_begin_send(soap) || soap_put_ns__ATTGetSessionID(soap, data, "ns:ATTGetSessionID", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__ATTGetSessionID * SOAP_FMAC4 soap_get_ns__ATTGetSessionID(struct soap*, struct ns__ATTGetSessionID *, const char*, const char*);

#ifndef soap_read_ns__ATTGetSessionID
#define soap_read_ns__ATTGetSessionID(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ATTGetSessionID(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__ATTGetSessionIDResponse
#define SOAP_TYPE_ns__ATTGetSessionIDResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__ATTGetSessionIDResponse(struct soap*, struct ns__ATTGetSessionIDResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__ATTGetSessionIDResponse(struct soap*, const struct ns__ATTGetSessionIDResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ATTGetSessionIDResponse(struct soap*, const char*, int, const struct ns__ATTGetSessionIDResponse *, const char*);
SOAP_FMAC3 struct ns__ATTGetSessionIDResponse * SOAP_FMAC4 soap_in_ns__ATTGetSessionIDResponse(struct soap*, const char*, struct ns__ATTGetSessionIDResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__ATTGetSessionIDResponse(struct soap*, const struct ns__ATTGetSessionIDResponse *, const char*, const char*);

#ifndef soap_write_ns__ATTGetSessionIDResponse
#define soap_write_ns__ATTGetSessionIDResponse(soap, data) ( soap_serialize_ns__ATTGetSessionIDResponse(soap, data), soap_begin_send(soap) || soap_put_ns__ATTGetSessionIDResponse(soap, data, "ns:ATTGetSessionIDResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__ATTGetSessionIDResponse * SOAP_FMAC4 soap_get_ns__ATTGetSessionIDResponse(struct soap*, struct ns__ATTGetSessionIDResponse *, const char*, const char*);

#ifndef soap_read_ns__ATTGetSessionIDResponse
#define soap_read_ns__ATTGetSessionIDResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ATTGetSessionIDResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__ATTReflash
#define SOAP_TYPE_ns__ATTReflash (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__ATTReflash(struct soap*, struct ns__ATTReflash *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__ATTReflash(struct soap*, const struct ns__ATTReflash *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ATTReflash(struct soap*, const char*, int, const struct ns__ATTReflash *, const char*);
SOAP_FMAC3 struct ns__ATTReflash * SOAP_FMAC4 soap_in_ns__ATTReflash(struct soap*, const char*, struct ns__ATTReflash *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__ATTReflash(struct soap*, const struct ns__ATTReflash *, const char*, const char*);

#ifndef soap_write_ns__ATTReflash
#define soap_write_ns__ATTReflash(soap, data) ( soap_serialize_ns__ATTReflash(soap, data), soap_begin_send(soap) || soap_put_ns__ATTReflash(soap, data, "ns:ATTReflash", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__ATTReflash * SOAP_FMAC4 soap_get_ns__ATTReflash(struct soap*, struct ns__ATTReflash *, const char*, const char*);

#ifndef soap_read_ns__ATTReflash
#define soap_read_ns__ATTReflash(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ATTReflash(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__ATTReflashResponse
#define SOAP_TYPE_ns__ATTReflashResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__ATTReflashResponse(struct soap*, struct ns__ATTReflashResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__ATTReflashResponse(struct soap*, const struct ns__ATTReflashResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ATTReflashResponse(struct soap*, const char*, int, const struct ns__ATTReflashResponse *, const char*);
SOAP_FMAC3 struct ns__ATTReflashResponse * SOAP_FMAC4 soap_in_ns__ATTReflashResponse(struct soap*, const char*, struct ns__ATTReflashResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__ATTReflashResponse(struct soap*, const struct ns__ATTReflashResponse *, const char*, const char*);

#ifndef soap_write_ns__ATTReflashResponse
#define soap_write_ns__ATTReflashResponse(soap, data) ( soap_serialize_ns__ATTReflashResponse(soap, data), soap_begin_send(soap) || soap_put_ns__ATTReflashResponse(soap, data, "ns:ATTReflashResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__ATTReflashResponse * SOAP_FMAC4 soap_get_ns__ATTReflashResponse(struct soap*, struct ns__ATTReflashResponse *, const char*, const char*);

#ifndef soap_read_ns__ATTReflashResponse
#define soap_read_ns__ATTReflashResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ATTReflashResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_stStrList
#define SOAP_TYPE_stStrList (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_stStrList(struct soap*, struct stStrList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_stStrList(struct soap*, struct stStrList const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_stStrList(struct soap*, const char*, int, const struct stStrList *, const char*);
SOAP_FMAC3 struct stStrList * SOAP_FMAC4 soap_in_stStrList(struct soap*, const char*, struct stStrList *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_stStrList(struct soap*, const struct stStrList *, const char*, const char*);

#ifndef soap_write_stStrList
#define soap_write_stStrList(soap, data) ( soap_serialize_stStrList(soap, data), soap_begin_send(soap) || soap_put_stStrList(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct stStrList * SOAP_FMAC4 soap_get_stStrList(struct soap*, struct stStrList *, const char*, const char*);

#ifndef soap_read_stStrList
#define soap_read_stStrList(soap, data) ( soap_begin_recv(soap) || !soap_get_stStrList(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__StrPointer
#define SOAP_TYPE_ns__StrPointer (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__StrPointer(struct soap*, struct ns__StrPointer *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__StrPointer(struct soap*, struct ns__StrPointer const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__StrPointer(struct soap*, const char*, int, const struct ns__StrPointer *, const char*);
SOAP_FMAC3 struct ns__StrPointer * SOAP_FMAC4 soap_in_ns__StrPointer(struct soap*, const char*, struct ns__StrPointer *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__StrPointer(struct soap*, const struct ns__StrPointer *, const char*, const char*);

#ifndef soap_write_ns__StrPointer
#define soap_write_ns__StrPointer(soap, data) ( soap_serialize_ns__StrPointer(soap, data), soap_begin_send(soap) || soap_put_ns__StrPointer(soap, data, "ns:StrPointer", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__StrPointer * SOAP_FMAC4 soap_get_ns__StrPointer(struct soap*, struct ns__StrPointer *, const char*, const char*);

#ifndef soap_read_ns__StrPointer
#define soap_read_ns__StrPointer(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__StrPointer(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__SendMsg
#define SOAP_TYPE_ns__SendMsg (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__SendMsg(struct soap*, struct ns__SendMsg *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__SendMsg(struct soap*, const struct ns__SendMsg *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__SendMsg(struct soap*, const char*, int, const struct ns__SendMsg *, const char*);
SOAP_FMAC3 struct ns__SendMsg * SOAP_FMAC4 soap_in_ns__SendMsg(struct soap*, const char*, struct ns__SendMsg *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__SendMsg(struct soap*, const struct ns__SendMsg *, const char*, const char*);

#ifndef soap_write_ns__SendMsg
#define soap_write_ns__SendMsg(soap, data) ( soap_serialize_ns__SendMsg(soap, data), soap_begin_send(soap) || soap_put_ns__SendMsg(soap, data, "ns:SendMsg", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__SendMsg * SOAP_FMAC4 soap_get_ns__SendMsg(struct soap*, struct ns__SendMsg *, const char*, const char*);

#ifndef soap_read_ns__SendMsg
#define soap_read_ns__SendMsg(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__SendMsg(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__SendMsgResponse
#define SOAP_TYPE_ns__SendMsgResponse (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__SendMsgResponse(struct soap*, struct ns__SendMsgResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__SendMsgResponse(struct soap*, const struct ns__SendMsgResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__SendMsgResponse(struct soap*, const char*, int, const struct ns__SendMsgResponse *, const char*);
SOAP_FMAC3 struct ns__SendMsgResponse * SOAP_FMAC4 soap_in_ns__SendMsgResponse(struct soap*, const char*, struct ns__SendMsgResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__SendMsgResponse(struct soap*, const struct ns__SendMsgResponse *, const char*, const char*);

#ifndef soap_write_ns__SendMsgResponse
#define soap_write_ns__SendMsgResponse(soap, data) ( soap_serialize_ns__SendMsgResponse(soap, data), soap_begin_send(soap) || soap_put_ns__SendMsgResponse(soap, data, "ns:SendMsgResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__SendMsgResponse * SOAP_FMAC4 soap_get_ns__SendMsgResponse(struct soap*, struct ns__SendMsgResponse *, const char*, const char*);

#ifndef soap_read_ns__SendMsgResponse
#define soap_read_ns__SendMsgResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__SendMsgResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_stMsg
#define SOAP_TYPE_stMsg (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_stMsg(struct soap*, struct stMsg *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_stMsg(struct soap*, const struct stMsg *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_stMsg(struct soap*, const char*, int, const struct stMsg *, const char*);
SOAP_FMAC3 struct stMsg * SOAP_FMAC4 soap_in_stMsg(struct soap*, const char*, struct stMsg *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_stMsg(struct soap*, const struct stMsg *, const char*, const char*);

#ifndef soap_write_stMsg
#define soap_write_stMsg(soap, data) ( soap_serialize_stMsg(soap, data), soap_begin_send(soap) || soap_put_stMsg(soap, data, "stMsg", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct stMsg * SOAP_FMAC4 soap_get_stMsg(struct soap*, struct stMsg *, const char*, const char*);

#ifndef soap_read_stMsg
#define soap_read_stMsg(soap, data) ( soap_begin_recv(soap) || !soap_get_stMsg(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_ns__MsgDataPointer
#define SOAP_TYPE_ns__MsgDataPointer (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__MsgDataPointer(struct soap*, struct ns__MsgDataPointer *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__MsgDataPointer(struct soap*, struct ns__MsgDataPointer const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__MsgDataPointer(struct soap*, const char*, int, const struct ns__MsgDataPointer *, const char*);
SOAP_FMAC3 struct ns__MsgDataPointer * SOAP_FMAC4 soap_in_ns__MsgDataPointer(struct soap*, const char*, struct ns__MsgDataPointer *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__MsgDataPointer(struct soap*, const struct ns__MsgDataPointer *, const char*, const char*);

#ifndef soap_write_ns__MsgDataPointer
#define soap_write_ns__MsgDataPointer(soap, data) ( soap_serialize_ns__MsgDataPointer(soap, data), soap_begin_send(soap) || soap_put_ns__MsgDataPointer(soap, data, "ns:MsgDataPointer", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__MsgDataPointer * SOAP_FMAC4 soap_get_ns__MsgDataPointer(struct soap*, struct ns__MsgDataPointer *, const char*, const char*);

#ifndef soap_read_ns__MsgDataPointer
#define soap_read_ns__MsgDataPointer(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__MsgDataPointer(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_serialize_PointerToSOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_serialize_PointerToSOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_serialize_PointerToSOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTostStrList
#define SOAP_TYPE_PointerTostStrList (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostStrList(struct soap*, struct stStrList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostStrList(struct soap*, const char *, int, struct stStrList *const*, const char *);
SOAP_FMAC3 struct stStrList ** SOAP_FMAC4 soap_in_PointerTostStrList(struct soap*, const char*, struct stStrList **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostStrList(struct soap*, struct stStrList *const*, const char*, const char*);

#ifndef soap_write_PointerTostStrList
#define soap_write_PointerTostStrList(soap, data) ( soap_serialize_PointerTostStrList(soap, data), soap_begin_send(soap) || soap_put_PointerTostStrList(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct stStrList ** SOAP_FMAC4 soap_get_PointerTostStrList(struct soap*, struct stStrList **, const char*, const char*);

#ifndef soap_read_PointerTostStrList
#define soap_read_PointerTostStrList(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostStrList(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTounsignedInt
#define SOAP_TYPE_PointerTounsignedInt (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedInt(struct soap*, unsigned int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedInt(struct soap*, const char *, int, unsigned int *const*, const char *);
SOAP_FMAC3 unsigned int ** SOAP_FMAC4 soap_in_PointerTounsignedInt(struct soap*, const char*, unsigned int **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedInt(struct soap*, unsigned int *const*, const char*, const char*);

#ifndef soap_write_PointerTounsignedInt
#define soap_write_PointerTounsignedInt(soap, data) ( soap_serialize_PointerTounsignedInt(soap, data), soap_begin_send(soap) || soap_put_PointerTounsignedInt(soap, data, "unsignedInt", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 unsigned int ** SOAP_FMAC4 soap_get_PointerTounsignedInt(struct soap*, unsigned int **, const char*, const char*);

#ifndef soap_read_PointerTounsignedInt
#define soap_read_PointerTounsignedInt(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTounsignedInt(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTons__StrPointer
#define SOAP_TYPE_PointerTons__StrPointer (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__StrPointer(struct soap*, struct ns__StrPointer *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__StrPointer(struct soap*, const char *, int, struct ns__StrPointer *const*, const char *);
SOAP_FMAC3 struct ns__StrPointer ** SOAP_FMAC4 soap_in_PointerTons__StrPointer(struct soap*, const char*, struct ns__StrPointer **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__StrPointer(struct soap*, struct ns__StrPointer *const*, const char*, const char*);

#ifndef soap_write_PointerTons__StrPointer
#define soap_write_PointerTons__StrPointer(soap, data) ( soap_serialize_PointerTons__StrPointer(soap, data), soap_begin_send(soap) || soap_put_PointerTons__StrPointer(soap, data, "ns:StrPointer", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns__StrPointer ** SOAP_FMAC4 soap_get_PointerTons__StrPointer(struct soap*, struct ns__StrPointer **, const char*, const char*);

#ifndef soap_read_PointerTons__StrPointer
#define soap_read_PointerTons__StrPointer(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__StrPointer(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTostMsg
#define SOAP_TYPE_PointerTostMsg (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostMsg(struct soap*, struct stMsg *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostMsg(struct soap*, const char *, int, struct stMsg *const*, const char *);
SOAP_FMAC3 struct stMsg ** SOAP_FMAC4 soap_in_PointerTostMsg(struct soap*, const char*, struct stMsg **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostMsg(struct soap*, struct stMsg *const*, const char*, const char*);

#ifndef soap_write_PointerTostMsg
#define soap_write_PointerTostMsg(soap, data) ( soap_serialize_PointerTostMsg(soap, data), soap_begin_send(soap) || soap_put_PointerTostMsg(soap, data, "stMsg", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct stMsg ** SOAP_FMAC4 soap_get_PointerTostMsg(struct soap*, struct stMsg **, const char*, const char*);

#ifndef soap_read_PointerTostMsg
#define soap_read_PointerTostMsg(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostMsg(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);

#ifndef soap_write_PointerTounsignedByte
#define soap_write_PointerTounsignedByte(soap, data) ( soap_serialize_PointerTounsignedByte(soap, data), soap_begin_send(soap) || soap_put_PointerTounsignedByte(soap, data, "unsignedByte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);

#ifndef soap_read_PointerTounsignedByte
#define soap_read_PointerTounsignedByte(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTounsignedByte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_serialize__QName(soap, data), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_serialize_string(soap, data), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
