/* soapServer.c
   Generated by gSOAP 2.8.15 from soapmsg.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.15 2013-09-12 08:43:37 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:SendMsg"))
		return soap_serve_ns__SendMsg(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:ATTReflash"))
		return soap_serve_ns__ATTReflash(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:ATTGetSessionID"))
		return soap_serve_ns__ATTGetSessionID(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:ATTGetTraceName"))
		return soap_serve_ns__ATTGetTraceName(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:ATTGetAnalyseName"))
		return soap_serve_ns__ATTGetAnalyseName(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:ATTGetAnalyse"))
		return soap_serve_ns__ATTGetAnalyse(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__SendMsg(struct soap *soap)
{	struct ns__SendMsg soap_tmp_ns__SendMsg;
	struct ns__SendMsgResponse soap_tmp_ns__SendMsgResponse;
	struct stMsg soap_tmp_stMsg;
	soap_default_ns__SendMsgResponse(soap, &soap_tmp_ns__SendMsgResponse);
	soap_default_stMsg(soap, &soap_tmp_stMsg);
	soap_tmp_ns__SendMsgResponse.out = &soap_tmp_stMsg;
	soap_default_ns__SendMsg(soap, &soap_tmp_ns__SendMsg);
	soap->encodingStyle = "";
	if (!soap_get_ns__SendMsg(soap, &soap_tmp_ns__SendMsg, "ns:SendMsg", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__SendMsg(soap, soap_tmp_ns__SendMsg.in, soap_tmp_ns__SendMsgResponse.out);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__SendMsgResponse(soap, &soap_tmp_ns__SendMsgResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__SendMsgResponse(soap, &soap_tmp_ns__SendMsgResponse, "ns:SendMsgResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__SendMsgResponse(soap, &soap_tmp_ns__SendMsgResponse, "ns:SendMsgResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__ATTReflash(struct soap *soap)
{	struct ns__ATTReflash soap_tmp_ns__ATTReflash;
	struct ns__ATTReflashResponse soap_tmp_ns__ATTReflashResponse;
	struct ns__StrPointer soap_tmp_ns__StrPointer;
	soap_default_ns__ATTReflashResponse(soap, &soap_tmp_ns__ATTReflashResponse);
	soap_default_ns__StrPointer(soap, &soap_tmp_ns__StrPointer);
	soap_tmp_ns__ATTReflashResponse.TraceStr = &soap_tmp_ns__StrPointer;
	soap_default_ns__ATTReflash(soap, &soap_tmp_ns__ATTReflash);
	soap->encodingStyle = "";
	if (!soap_get_ns__ATTReflash(soap, &soap_tmp_ns__ATTReflash, "ns:ATTReflash", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__ATTReflash(soap, soap_tmp_ns__ATTReflash.ID, soap_tmp_ns__ATTReflash.IP, soap_tmp_ns__ATTReflash.Port, soap_tmp_ns__ATTReflash.TraceName, soap_tmp_ns__ATTReflashResponse.TraceStr);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__ATTReflashResponse(soap, &soap_tmp_ns__ATTReflashResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__ATTReflashResponse(soap, &soap_tmp_ns__ATTReflashResponse, "ns:ATTReflashResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__ATTReflashResponse(soap, &soap_tmp_ns__ATTReflashResponse, "ns:ATTReflashResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__ATTGetSessionID(struct soap *soap)
{	struct ns__ATTGetSessionID soap_tmp_ns__ATTGetSessionID;
	struct ns__ATTGetSessionIDResponse soap_tmp_ns__ATTGetSessionIDResponse;
	unsigned int soap_tmp_unsignedInt;
	soap_default_ns__ATTGetSessionIDResponse(soap, &soap_tmp_ns__ATTGetSessionIDResponse);
	soap_default_unsignedInt(soap, &soap_tmp_unsignedInt);
	soap_tmp_ns__ATTGetSessionIDResponse.pID = &soap_tmp_unsignedInt;
	soap_default_ns__ATTGetSessionID(soap, &soap_tmp_ns__ATTGetSessionID);
	soap->encodingStyle = "";
	if (!soap_get_ns__ATTGetSessionID(soap, &soap_tmp_ns__ATTGetSessionID, "ns:ATTGetSessionID", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__ATTGetSessionID(soap, soap_tmp_ns__ATTGetSessionIDResponse.pID);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__ATTGetSessionIDResponse(soap, &soap_tmp_ns__ATTGetSessionIDResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__ATTGetSessionIDResponse(soap, &soap_tmp_ns__ATTGetSessionIDResponse, "ns:ATTGetSessionIDResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__ATTGetSessionIDResponse(soap, &soap_tmp_ns__ATTGetSessionIDResponse, "ns:ATTGetSessionIDResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__ATTGetTraceName(struct soap *soap)
{	struct ns__ATTGetTraceName soap_tmp_ns__ATTGetTraceName;
	struct ns__ATTGetTraceNameResponse soap_tmp_ns__ATTGetTraceNameResponse;
	struct stStrList soap_tmp_stStrList;
	soap_default_ns__ATTGetTraceNameResponse(soap, &soap_tmp_ns__ATTGetTraceNameResponse);
	soap_default_stStrList(soap, &soap_tmp_stStrList);
	soap_tmp_ns__ATTGetTraceNameResponse.out = &soap_tmp_stStrList;
	soap_default_ns__ATTGetTraceName(soap, &soap_tmp_ns__ATTGetTraceName);
	soap->encodingStyle = "";
	if (!soap_get_ns__ATTGetTraceName(soap, &soap_tmp_ns__ATTGetTraceName, "ns:ATTGetTraceName", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__ATTGetTraceName(soap, soap_tmp_ns__ATTGetTraceName.IP, soap_tmp_ns__ATTGetTraceName.Port, soap_tmp_ns__ATTGetTraceNameResponse.out);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__ATTGetTraceNameResponse(soap, &soap_tmp_ns__ATTGetTraceNameResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__ATTGetTraceNameResponse(soap, &soap_tmp_ns__ATTGetTraceNameResponse, "ns:ATTGetTraceNameResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__ATTGetTraceNameResponse(soap, &soap_tmp_ns__ATTGetTraceNameResponse, "ns:ATTGetTraceNameResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__ATTGetAnalyseName(struct soap *soap)
{	struct ns__ATTGetAnalyseName soap_tmp_ns__ATTGetAnalyseName;
	struct ns__ATTGetAnalyseNameResponse soap_tmp_ns__ATTGetAnalyseNameResponse;
	struct stStrList soap_tmp_stStrList;
	soap_default_ns__ATTGetAnalyseNameResponse(soap, &soap_tmp_ns__ATTGetAnalyseNameResponse);
	soap_default_stStrList(soap, &soap_tmp_stStrList);
	soap_tmp_ns__ATTGetAnalyseNameResponse.out = &soap_tmp_stStrList;
	soap_default_ns__ATTGetAnalyseName(soap, &soap_tmp_ns__ATTGetAnalyseName);
	soap->encodingStyle = "";
	if (!soap_get_ns__ATTGetAnalyseName(soap, &soap_tmp_ns__ATTGetAnalyseName, "ns:ATTGetAnalyseName", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__ATTGetAnalyseName(soap, soap_tmp_ns__ATTGetAnalyseName.IP, soap_tmp_ns__ATTGetAnalyseName.Port, soap_tmp_ns__ATTGetAnalyseNameResponse.out);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__ATTGetAnalyseNameResponse(soap, &soap_tmp_ns__ATTGetAnalyseNameResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__ATTGetAnalyseNameResponse(soap, &soap_tmp_ns__ATTGetAnalyseNameResponse, "ns:ATTGetAnalyseNameResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__ATTGetAnalyseNameResponse(soap, &soap_tmp_ns__ATTGetAnalyseNameResponse, "ns:ATTGetAnalyseNameResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__ATTGetAnalyse(struct soap *soap)
{	struct ns__ATTGetAnalyse soap_tmp_ns__ATTGetAnalyse;
	struct ns__ATTGetAnalyseResponse soap_tmp_ns__ATTGetAnalyseResponse;
	struct ns__StrPointer soap_tmp_ns__StrPointer;
	soap_default_ns__ATTGetAnalyseResponse(soap, &soap_tmp_ns__ATTGetAnalyseResponse);
	soap_default_ns__StrPointer(soap, &soap_tmp_ns__StrPointer);
	soap_tmp_ns__ATTGetAnalyseResponse.AnalyseStr = &soap_tmp_ns__StrPointer;
	soap_default_ns__ATTGetAnalyse(soap, &soap_tmp_ns__ATTGetAnalyse);
	soap->encodingStyle = "";
	if (!soap_get_ns__ATTGetAnalyse(soap, &soap_tmp_ns__ATTGetAnalyse, "ns:ATTGetAnalyse", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__ATTGetAnalyse(soap, soap_tmp_ns__ATTGetAnalyse.IP, soap_tmp_ns__ATTGetAnalyse.Port, soap_tmp_ns__ATTGetAnalyse.AnalyseName, soap_tmp_ns__ATTGetAnalyseResponse.AnalyseStr);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__ATTGetAnalyseResponse(soap, &soap_tmp_ns__ATTGetAnalyseResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__ATTGetAnalyseResponse(soap, &soap_tmp_ns__ATTGetAnalyseResponse, "ns:ATTGetAnalyseResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__ATTGetAnalyseResponse(soap, &soap_tmp_ns__ATTGetAnalyseResponse, "ns:ATTGetAnalyseResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
